### ISSUE TITLE
项目文件不完整

### ISSUE THREAD

**Issue by JinkunTian** [Ncerzzk/Brushless_Driver_Nosensor#1]
学长你好，项目中使用了as5047.c和dma.c两个文件，但是git源中并没有这两个文件。并且也找不到Get_Position()函数的原型。能不能看一看是不是漏添加了呢。

**Comment by Ncerzzk** [comment]
as5047.c 和 dma.c 应该在：https://github.com/Ncerzzk/driverslib 中。

**Comment by Ncerzzk** [comment]
另外，这份硬件和代码应该是比较久远了，如果你要自己理解无感无刷驱动可以参考一下。
我后来都使用https://github.com/Ncerzzk/BrushlessFoc_Hardware/  这份 可以跑FOC的硬件 + VESC 固件了。

**Comment by JinkunTian** [comment]
好的，谢谢。
